// This file is auto-generated by @hey-api/openapi-ts

export const RegisterDtoSchema = {
  type: 'object',
  properties: {
    email: {
      type: 'string',
      description: 'User Email',
      example: 'email@example.com',
    },
    password: {
      type: 'string',
      description: 'User Password',
      example: 'password',
      minLength: 8,
    },
    name: {
      type: 'string',
      description: 'User Name',
      example: 'Daniil',
    },
    secondName: {
      type: 'string',
      description: 'User Second Name',
      example: 'Frei',
    },
    birthDate: {
      type: 'string',
      description: 'User BirthDate',
      example: 'Frei',
    },
  },
  required: ['email', 'password', 'name'],
} as const;

export const AuthResultDtoSchema = {
  type: 'object',
  properties: {
    accessToken: {
      type: 'string',
      description: 'User Token to access api',
      example:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYmIyNmNjMS1lMTNlLTQwZTYtOTM1Zi05YmY1NjgyYTMzOGMiLCJpYXQiOjE1MTYyMzkwMjJ9.8w8zXFQf9ThFBbNdXm-UPv6chlEL3cdjmS9mouEkG3A',
    },
  },
  required: ['accessToken'],
} as const;

export const LoginDtoSchema = {
  type: 'object',
  properties: {
    email: {
      type: 'string',
      description: 'User Email',
      example: 'email@example.com',
    },
    password: {
      type: 'string',
      description: 'User Password',
      example: 'password',
      minLength: 8,
    },
  },
  required: ['email', 'password'],
} as const;

export const FindByIdUserResultDtoSchema = {
  type: 'object',
  properties: {
    email: {
      type: 'string',
      description: 'User Email',
      example: 'email@example.com',
    },
    name: {
      type: 'string',
      description: 'User Name',
      example: 'Daniil',
    },
    secondName: {
      type: 'string',
      description: 'User Second Name',
      example: 'Frei',
    },
    birthDate: {
      type: 'string',
      description: 'User BirthDate',
      example: 'Frei',
    },
    id: {
      type: 'string',
      description: 'User Id',
      example: 'ebb26cc1-e13e-40e6-935f-9bf5682a338c',
    },
  },
  required: ['email', 'name', 'id'],
} as const;

export const UpdateUserDtoSchema = {
  type: 'object',
  properties: {
    email: {
      type: 'string',
      description: 'User Email',
      example: 'email@example.com',
    },
    name: {
      type: 'string',
      description: 'User Name',
      example: 'Daniil',
    },
    secondName: {
      type: 'string',
      description: 'User Second Name',
      example: 'Frei',
    },
    birthDate: {
      type: 'string',
      description: 'User BirthDate',
      example: 'Frei',
    },
  },
} as const;

export const UpdateUserResultDtoSchema = {
  type: 'object',
  properties: {
    email: {
      type: 'string',
      description: 'User Email',
      example: 'email@example.com',
    },
    name: {
      type: 'string',
      description: 'User Name',
      example: 'Daniil',
    },
    secondName: {
      type: 'string',
      description: 'User Second Name',
      example: 'Frei',
    },
    birthDate: {
      type: 'string',
      description: 'User BirthDate',
      example: 'Frei',
    },
    id: {
      type: 'string',
      description: 'User Id',
      example: 'ebb26cc1-e13e-40e6-935f-9bf5682a338c',
    },
  },
  required: ['email', 'name', 'id'],
} as const;

export const DeleteUserResultDtoSchema = {
  type: 'object',
  properties: {
    success: {
      type: 'boolean',
      description: 'Deleting result',
      example: true,
    },
  },
  required: ['success'],
} as const;
