version: '3.8'

services:
  be:
    image: be
    container_name: be
    hostname: be
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - beck-end-network

  db:
    image: mysql:8.0
    container_name: db
    hostname: db
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 10s
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - beck-end-network

networks:
  beck-end-network:
    driver: bridge
volumes:
  db_data:
